// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApi.Data;

#nullable disable

namespace MovieApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230921031716_AddLocalPath")]
    partial class AddLocalPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdat = new DateTime(2023, 9, 21, 10, 17, 16, 256, DateTimeKind.Local).AddTicks(8883),
                            description = "Film Horor tahun2022",
                            image = "",
                            rating = 7f,
                            title = "Pengabdi Setan 2",
                            updatedat = new DateTime(2023, 9, 21, 10, 17, 16, 256, DateTimeKind.Local).AddTicks(8893)
                        },
                        new
                        {
                            id = 2,
                            createdat = new DateTime(2023, 9, 21, 10, 17, 16, 256, DateTimeKind.Local).AddTicks(8896),
                            description = "Film Horor tahun2022",
                            image = "",
                            rating = 8f,
                            title = "Pengabdi Setan 1",
                            updatedat = new DateTime(2023, 9, 21, 10, 17, 16, 256, DateTimeKind.Local).AddTicks(8897)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
